version: "3"
services:
  web:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - blog-network
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blogdb
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - blog-network
volumes:
  db-data:
networks:
  blog-network:
